### ISSUE TITLE
Crash initializing a Variant with an object

### ISSUE THREAD

**Issue by nvanfleet** [migueldeicaza/SwiftGodot#79]
I got this crash when I was trying to initialize a Variant with a `ViewportTexture` instance.

The Swift code is as such
```
    private func setupColorRect(_ colorRect: ColorRect) {
        guard let viewport = self.viewport else {
            return Log.log("Missing ViewPort")
        }
        
        guard let texture = viewport.getTexture() else {
            return Log.log("Missing texture")
        }
        
        guard let shaderMaterial = colorRect.material as? ShaderMaterial else {
            return Log.log("Missing shaderMaterial")
        }
        
        self.colorRect?.visible = false
        shaderMaterial.setShaderParameter(param: "portal_texture", value: Variant(texture))
    }
```

```

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGBUS)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x0000000108312a18
Exception Codes:       0x0000000000000002, 0x0000000108312a18

Termination Reason:    Namespace SIGNAL, Code 10 Bus error: 10
Terminating Process:   exc handler [27410]

VM Region Info: 0x108312a18 is in 0x1081f8000-0x1083ec000;  bytes after start: 1157656  bytes before end: 890343
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      __TEXT                      10247c000-1081f8000    [ 93.5M] r-x/r-x SM=COW  ...s/MacOS/Godot
--->  __DATA_CONST                1081f8000-1083ec000    [ 2000K] r--/rw- SM=COW  ...s/MacOS/Godot
      __DATA                      1083ec000-108424000    [  224K] rw-/rw- SM=COW  ...s/MacOS/Godot

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   Godot                         	       0x10644cbdc 0x10247c000 + 66915292
1   Godot                         	       0x10644cb70 0x10247c000 + 66915184
2   Godot                         	       0x1062e436c 0x10247c000 + 65438572
3   libSwiftGodot.dylib           	       0x10ffad080 Variant.init(_:) + 120 (Variant.swift:240)
4   libPlantQuest.dylib           	       0x10e117d00 Variant.__allocating_init(_:) + 4 [inlined]
5   libPlantQuest.dylib           	       0x10e117d00 PictureLoop.setupColorRect(_:) + 328 (PictureLoop.swift:65)
6   libPlantQuest.dylib           	       0x10e11fccc PictureLoop.colorRect.didset + 24 (PictureLoop.swift:12) [inlined]
7   libPlantQuest.dylib           	       0x10e11fccc PictureLoop.colorRect.setter + 24 [inlined]
8   libPlantQuest.dylib           	       0x10e11fccc PlayerCharacter._ready() + 156 (PlayerCharacter.swift:28)
9   libSwiftGodot.dylib           	       0x1102cb6f4 _Node_proxy_ready(instance:args:retPtr:) + 36 (Node.swift:1660) [inlined]
10  libSwiftGodot.dylib           	       0x1102cb6f4 @objc _Node_proxy_ready(instance:args:retPtr:) + 36 (<compiler-generated>:1657)
```

**Comment by nvanfleet** [comment]
The easiest repro steps for this is 

```
        let standard = StandardMaterial3D()
        let variant = Variant(standard.metallicTexture)
```

**Comment by migueldeicaza** [comment]
Fixed, the problem was that it is not possible to create a Variant of type object when the parameter is null.  So instead, this initializes a Variant of type nil.

In your case, the standard.metallicTexture was nil

**Comment by nvanfleet** [comment]
Hmmm okay, my first example there is a guard that makes sure it's not nil though. It was still definitely crashing for 0.14 but I can check with the other changes.

**Comment by nvanfleet** [comment]
Yeah @migueldeicaza I verified this is still crashing in the scenario that you ensure it's not nil. 

```
0   Godot                         	       0x1060b4bdc 0x1020e4000 + 66915292
1   Godot                         	       0x1060b4b70 0x1020e4000 + 66915184
2   Godot                         	       0x105f4c36c 0x1020e4000 + 65438572
3   libSwiftGodot.dylib           	       0x10fc21e38 Variant.init(_:) + 120 (Variant.swift:240)
4   libPlantQuest.dylib           	       0x10dd886ac Variant.__allocating_init(_:) + 4 [inlined]
```

So the test could be

```
guard let viewport = self.viewport else {
     return
}

let variant = Variant(viewport)
```

Sorry about that I didn't realize there would be a difference between the optional case :|
